import styles from '@/app/blog/blog.module.scss';
import BlogCard from '../ui/molecules/BlogCard';
import BreadCrumbs from '../ui/atoms/BreadCrumbs';
import BlogArticleList from '../ui/molecules/BlogArticleList';
import BlogNavigation from '../ui/molecules/BlogNavigation';
import { use } from 'react';
import { getPage } from '../utils/cocntentful';

async function getPageData () {
  return await getPage({
   pageContentType: 'blogItem',
   locale: 'en-US',
   limit: 1000
 }, false);
}

export const metadata = {
  title: 'Coder in Austria | Blog',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/favicon.ico',
  },
}

export default function Blog() {
  const data = use(getPageData());
  console.log(data);
  
  const blogCard = {
    tag: {
      color: 'red',
      isSmall: false,
      title: 'JS'
    },
    title: 'Lorem ipsum Lorem ipsum Lorem ipsum ',
    date: 'Dec 06, 2023',
    image: 'blog_card.png',
    url: '/blog/123'
  };

  const breadCrumbs = {
    items: [
      {
        title: 'Home',
        isLast: false,
        url: '/'
      },
      {
        title: 'Blog',
        isLast: true
      }
    ]
  };

  const blogNavigation = {
    popularBlogs: [
      {
          image: '/popular_blog.png',
          title: 'If you read one article about summer outfits read this one',
          date: 'Dec 06, 2016',
          url: '/blog/123',
          id: '123'
      },
      {
          image: '/popular_blog.png',
          title: 'If you read one article about summer outfits read this one',
          date: 'Dec 06, 2016',
          url: '/blog/123',
          id: '1234'
      },
      {
          image: '/popular_blog.png',
          title: 'If you read one article about summer outfits read this one',
          date: 'Dec 06, 2016',
          url: '/blog/123',
          id: '1235'
      }
    ],
    categories: [
      {
        title: 'Programming',
        url: 'blog/category/programming'
      },
      {
        title: 'Traveling',
        url: 'blog/category/traveling'
      },
      {
        title: 'Lifestyle',
        url: 'blog/category/lifestyle'
      }
    ],
    tags: [
      {
        title: 'JS',
        url: '/blog/tags/JS',
        color: 'red',
        isSmall: true
      },
      {
        title: 'MongoDB',
        url: '/blog/tags/MongoDB',
        color: 'middleBlue',
        isSmall: true
      },
      {
        title: 'ReactJS',
        url: '/blog/tags/ReactJS',
        color: 'darkBlue',
        isSmall: true
      }
    ]
  }

  const blog = {
    items:[
      {
          tag: {
              color: 'red',
              isSmall: false,
              title: 'JS'
          },
          title: 'Lorem ipsum Lorem ipsum Lorem ipsum ',
          text: 'The unconventional guide to unique dresses. Cheap cloths by the numbers. The evolution of fashion magazines. 18 things your boss expects you ',
          date: 'Dec 06, 2023',
          url: '/blog/123',
          image: 'blog_card.png'
      },
      {
          tag: {
              color: 'red',
              isSmall: false,
              title: 'JS'
          },
          title: 'Lorem ipsum Lorem ipsum Lorem ipsum ',
          text: 'The unconventional guide to unique dresses. Cheap cloths by the numbers. The evolution of fashion magazines. 18 things your boss expects you ',
          date: 'Dec 06, 2023',
          url: '/blog/1235',
          image: 'blog_card.png'
      },
      {
          tag: {
              color: 'red',
              isSmall: false,
              title: 'JS'
          },
          title: 'Lorem ipsum Lorem ipsum Lorem ipsum ',
          text: 'The unconventional guide to unique dresses. Cheap cloths by the numbers. The evolution of fashion magazines. 18 things your boss expects you ',
          date: 'Dec 06, 2023',
          url: '/blog/1234',
          image: 'blog_card.png'
      }
  ]
  }

  return (
    <main>
      <div className={`${styles.blog} content`}>
        <BreadCrumbs {...breadCrumbs} />
        <h1>Blog</h1>
        <div className={styles.blog__recomended}>
          <BlogCard {...blogCard}/>
          <BlogCard {...blogCard}/>
          <BlogCard {...blogCard}/>
        </div>

        <div className={styles.blog__blogContent}>
          <div className={styles.blog__blogContent__left}>
            <BlogArticleList {...blog} />
          </div>
          <div className={styles.blog__blogContent__right}>
            <BlogNavigation {...blogNavigation} />
          </div>
        </div>
      </div>
    </main>
  )
}