import Footer from './components/Footer'
import Header from './components/Header'
import './globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <title>Coder in Austria</title>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
