import './globals.scss';
import { JetBrains_Mono } from 'next/font/google';

const jetBrains = JetBrains_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Coder in Austria',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={jetBrains.className}>
        {children}
      </body>
    </html>
  )
}
