import './globals.scss'
import { JetBrains_Mono } from 'next/font/google'
import Header from './ui/organisms/Header'
import Footer from './ui/organisms/Footer'

const jetBrains = JetBrains_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Coder in Austria',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={jetBrains.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
